include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Avoid print statements in production
    avoid_print: true
    
    # Prefer const constructors
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    
    # Use key in widget constructors
    use_key_in_widget_constructors: true
    
    # Prefer final for variables
    prefer_final_fields: true
    prefer_final_locals: true
    
    # Avoid empty statements
    avoid_empty_else: true
    
    # Use proper naming conventions
    camel_case_types: true
    camel_case_extensions: true
    file_names: true
    
    # Prefer single quotes
    prefer_single_quotes: true
    
    # Avoid unnecessary imports
    avoid_unused_constructor_parameters: true
    
    # Documentation
    public_member_api_docs: false # Set to true if you want to enforce documentation
    
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  
  errors:
    invalid_annotation_target: ignore
